services:
  - type: web
    name: gantal-store
    runtime: go
    plan: free
    buildCommand: go build -o server .
    startCommand: ./server
    envVars:
      - key: PORT
        value: 10000
      - key: STATIC_DIR
        value: static
